export const HOME = '/'
export const DASHBOARD = '/admin'
export const LOGIN = '/admin/login'
export const CREATE_USER = '/admin/create/user'
export const UPDATE_USER = '/admin/update/user/:id'
export const CREATE_VOTING = '/admin/create/voting'
export const LIST_USERS = '/admin/list/user/'
export const RECOVER_PASSWORD = '/admin/user/recover'
